<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="1608" started-at="2019-02-12T13:17:19Z" finished-at="2019-02-12T13:17:20Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="1608" started-at="2019-02-12T13:17:19Z" finished-at="2019-02-12T13:17:20Z">
      <class name="Testcase.RegressionTest">
        <test-method status="PASS" signature="getExcel()[pri:0, instance:Testcase.RegressionTest@293a5bf6]" name="getExcel" is-config="true" duration-ms="27" started-at="2019-02-12T13:17:19Z" finished-at="2019-02-12T13:17:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getExcel -->
        <test-method status="PASS" signature="hitClientResource()[pri:0, instance:Testcase.RegressionTest@293a5bf6]" name="hitClientResource" is-config="true" duration-ms="539" started-at="2019-02-12T13:17:19Z" finished-at="2019-02-12T13:17:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- hitClientResource -->
        <test-method status="FAIL" signature="regression_Home_CLP_PLP_Search()[pri:0, instance:Testcase.RegressionTest@293a5bf6]" name="regression_Home_CLP_PLP_Search" duration-ms="1008" started-at="2019-02-12T13:17:19Z" finished-at="2019-02-12T13:17:20Z">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index: 1, Size: 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at generalUtilities.BaseTest.Home_CLP_PLP_Search_data(BaseTest.java:94)
at functaionalities.Home_CLP_PLP_Search.contentMethod(Home_CLP_PLP_Search.java:25)
at Testcase.RegressionTest.regression_Home_CLP_PLP_Search(RegressionTest.java:30)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- regression_Home_CLP_PLP_Search -->
      </class> <!-- Testcase.RegressionTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
